# Generated by Django 4.2.15 on 2024-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(default='slug1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
