# Generated by Django 4.2.15 on 2024-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_category_options_alter_husband_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='womantag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='women',
            name='slug',
        ),
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='women/<django.db.models.fields.CharField>/'),
        ),
    ]
