# Generated by Django 4.2.15 on 2024-08-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_remove_category_slug_remove_womantag_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Woman',
        ),
        migrations.RenameIndex(
            model_name='woman',
            new_name='women_woman_time_cr_0d1543_idx',
            old_name='women_women_time_cr_9f33c2_idx',
        ),
    ]
