# Generated by Django 4.2.15 on 2024-08-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0006_rename_women_woman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='women', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
